//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseMigrator.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLFileProvider {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLFileProvider() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataBaseMigrator.SQL.SQLFileProvider", typeof(SQLFileProvider).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Script for SelectTopNRows command from SSMS  ******/
        ///SELECT [eEmployees1Id]
        ///      ,[UserAccountId]
        ///      ,[ID_employee]
        ///      ,[Surname]
        ///      ,[Name]
        ///      ,[Patronymic]
        ///      ,[ID_Sex]
        ///      ,[SexName]
        ///      ,[id_sector]
        ///      ,[SectorName]
        ///      ,[ID_Subdivision]
        ///      ,[SubdivName]
        ///      ,[ID_Duties]
        ///      ,[DutiesName]
        ///      ,[Id_DutiesSubtype]
        ///      ,[DutiesSubTypeName]
        ///      ,[ID_Group]
        ///      ,[GroupName]
        ///      ,[ContractDocumentEndDate]
        ///      ,[ID_AcademicDegree]
        ///      , [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectByConditionFromCampusTable {
            get {
                return ResourceManager.GetString("SelectByConditionFromCampusTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Script for SelectTopNRows command from SSMS  ******/
        ///SELECT [RowNumber]
        ///      ,[ID_employee]
        ///      ,[Surname]
        ///      ,[Name]
        ///      ,[Patronymic]
        ///      ,[ID_Sex]
        ///      ,[SexName]
        ///      ,[id_sector]
        ///      ,[SectorName]
        ///      ,[ID_Subdivision]
        ///      ,[SubdivName]
        ///      ,[ID_Duties]
        ///      ,[DutiesName]
        ///      ,[Id_DutiesSubtype]
        ///      ,[DutiesSubTypeName]
        ///      ,[ID_Group]
        ///      ,[GroupName]
        ///      ,[ContractDocumentEndDate]
        ///      ,[ID_DCAcademicDegree]
        ///      ,[AcademicDegreeName]
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectByConditionFromViewVKD {
            get {
                return ResourceManager.GetString("SelectByConditionFromViewVKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Script for SelectTopNRows command from SSMS  ******/
        ///SELECT [eEmployees1Id]
        ///      ,[UserAccountId]
        ///      ,[ID_employee]
        ///      ,[Surname]
        ///      ,[Name]
        ///      ,[Patronymic]
        ///      ,[ID_Sex]
        ///      ,[SexName]
        ///      ,[id_sector]
        ///      ,[SectorName]
        ///      ,[ID_Subdivision]
        ///      ,[SubdivName]
        ///      ,[ID_Duties]
        ///      ,[DutiesName]
        ///      ,[Id_DutiesSubtype]
        ///      ,[DutiesSubTypeName]
        ///      ,[ID_Group]
        ///      ,[GroupName]
        ///      ,[ContractDocumentEndDate]
        ///      ,[ID_AcademicDegree]
        ///      , [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectRangeFromCampusTable {
            get {
                return ResourceManager.GetString("SelectRangeFromCampusTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Script for SelectTopNRows command from SSMS  ******/
        ///SELECT [RowNumber]
        ///      ,[ID_employee]
        ///      ,[Surname]
        ///      ,[Name]
        ///      ,[Patronymic]
        ///      ,[ID_Sex]
        ///      ,[SexName]
        ///      ,[id_sector]
        ///      ,[SectorName]
        ///      ,[ID_Subdivision]
        ///      ,[SubdivName]
        ///      ,[ID_Duties]
        ///      ,[DutiesName]
        ///      ,[Id_DutiesSubtype]
        ///      ,[DutiesSubTypeName]
        ///      ,[ID_Group]
        ///      ,[GroupName]
        ///      ,[ContractDocumentEndDate]
        ///      ,[ID_DCAcademicDegree]
        ///      ,[AcademicDegreeName]
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectRangeFromViewVKD {
            get {
                return ResourceManager.GetString("SelectRangeFromViewVKD", resourceCulture);
            }
        }
    }
}
